from myStream import *
if __name__ == "__main__":
    n = myStream(6)
    n.updateStream(1)
    print(n.getStream())
    n.updateStream(2)
    print(n.getStream())
    n.updateStream(3)
    print(n.getStream())
    n.updateStream(4)
    print(n.getStream())
    n.updateStream(5)
    print(n.getStream())
    n.updateStream(6)
    print(n.getStream())
    n.updateStream(7)
    print(n.getStream())
    n.updateStream(8)
    print(n.getStream())
    print(n.getAverage())